# Generated by Django 5.0.1 on 2024-01-22 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 15, 14, 53, 211555), verbose_name='Опубликовать в'),
        ),
    ]
